on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DIRNAME: myapptest
      STACK_NAME: mybyeapp
      CLUSTER_NAME: mybyecluster
      SERVICE_NAME: mybyeservice
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      CDK_DEFAULT_REGION: us-east-2
      CDK_INFRASTRUCTURE_REPO: cdk-infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create and move files into $DIRNAME
        run: |
          mkdir $DIRNAME
          ls | grep -v $DIRNAME | xargs mv -t $DIRNAME
      - name: Cloning AWS CDK infrastructure
        run: git clone https://github.com/jsx101/cdk-infrastructure.git
      - name: Move $DIRNAME into cdk app and cd into it
        run: mv $DIRNAME $CDK_INFRASTRUCTURE_REPO
      - name: npm install
        run: cd $CDK_INFRASTRUCTURE_REPO && npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install 'cdk' command
        run: npm i -g aws-cdk
      - name: See directory structure
        run: cd $CDK_INFRASTRUCTURE_REPO && ls
      - name: cdk deploy
        run: cd $CDK_INFRASTRUCTURE_REPO && cdk deploy --context stackName=$STACK_NAME --context clusterName=$CLUSTER_NAME --context serviceName=$SERVICE_NAME --context assetFolder=$DIRNAME --require-approval never